### ISSUE TITLE
auto-archiving will automatically re-archive file

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/extractors-archival#5]
The auto-archiving code will check to see when a file was last downloaded. If this is more than X days ago, it will trigger an archive operation.

If we un-archive an old file, it will not be marked as downloaded recently, and thus will fairly quickly (next day) be re-archived. 

To fix this, in the unarchiving we should call the download function, but only download the first 10 bytes or so. This will mark a download happening in clowder, but does not take a long time to download the while file.

**Comment by bodom0015** [comment]
This was fixed by https://github.com/clowder-framework/clowder/pull/234. Feel free to close this one :+1: (I don't have permissions)
